import "./globals.css";
import RootLayoutClient from "./layout-client";

export const metadata = {
  title: "Car rental web app",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <RootLayoutClient>{children}</RootLayoutClient>
      </body>
    </html>
  );
}
